/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */


/**
 *
 * @author hp
 */

package gui;
import connexion.Connexion;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.lang.model.SourceVersion;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;


/**
 *
 * @author elabtahysanae
 */

public class Barchart extends javax.swing.JInternalFrame {

    private DefaultCategoryDataset dataset;
    private Connexion connexion;

    /**
     * Creates new form Barchart
     */
    public Barchart() {
        initComponents();
        connexion = Connexion.getInstance();
        this.setTitle("Répartition des comcours par participant");
        setSize(900, 800);
        

        dataset = new DefaultCategoryDataset();
        load();
        JFreeChart barChart = ChartFactory.createBarChart(
                "Répartition des concours",
                "resultat",
                "Nombre de concours",
                dataset
        );

        ChartPanel chartPanel = new ChartPanel(barChart);
        setContentPane(chartPanel);
    }

    private void load() {
        String req = "SELECT resultat, COUNT(*) AS nb_concours FROM Resultat GROUP BY resultat";

        try (PreparedStatement ps = connexion.getCn().prepareStatement(req);
                ResultSet rs = ps.executeQuery()) {

            dataset.clear();  // Efface les anciennes données

            while (rs.next()) {
                String resultat = rs.getString("resultat");
                int nbConcours = rs.getInt("nb_concours");
                dataset.addValue(nbConcours, "concours", resultat);
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erreur de connexion à la base de données !");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}